### ISSUE TITLE
Wakefield scrapbooks are broken

### ISSUE THREAD

**Issue by lweakly** [CDRH/data_transmississippi#1]
http://trans-mississippi.unl.edu/texts/scrapbooks.html

getting this error: java.io.FileNotFoundException: /var/local/www/cocoon/trans-mississippi.unl.edu/xml/documents/transmiss.sb.01.xml (No such file or directory)

**Comment by jduss4** [comment]
Huh, weird, I must not have clicked submit on my comment this morning, but there is no file by the name `transmiss.sb.01` in the cocoon site, though it is stored in solr with that id.  I'm guessing that cocoon should be parsing the solr response and selecting a particular portion of a scrapbook?

**Comment by jduss4** [comment]
Closing in favor of https://github.com/CDRH/CDRH-General/issues/138
